version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ericnov2021batch1_invdb
    volumes:
      - /data/mysql
    healthcheck:        
        interval: 30s
        timeout: 10s
        retries: 5
  
  inv-app:
    image: inv-appv2
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
      - 8060-8070:7070
    volumes:
      - /data/compose-app
      
      
 